server:
  port: 8080

spring:
  application:
    name: management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    springframework: INFO
    com:
      example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,metrics
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
    env:
      enabled: true
    metrics:
      enabled: true

jwt:
  secret: your-256-bit-secret-key-here-must-be-at-least-32-characters-long
  expiration: 86400000 # 24 hours in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds


